"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP_NAME = 'Periodic Table'
APP = ['main.py']
DATA_FILES = [('db', ['element_table/PeriodicTable.db'])]
OPTIONS = {
    'packages': ['kivy', 'info', 'SQL', 'GUI'],
    'argv_emulation': True,
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleVersion': '0.1.0 stable'
    }
}

setup(
    app=APP,
    name=APP_NAME,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
